//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancialServiceApplication.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\FinancialCons" +
            "ultantDB.mdf;Integrated Security=True;Connect Timeout=30")]
        public string FCDConnectionString {
            get {
                return ((string)(this["FCDConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;Initial Catalog=4619868F587328335CD4731366C17B" +
            "86_SERVICEAPPLICATIONSOLUTION-MAIN\\FINANCIALSERVICEAPPLICATION\\BIN\\DEBUG\\FINANCI" +
            "ALCONSULTANTDB.MDF;Integrated Security=True")]
        public string _4619868F587328335CD4731366C17B86_SERVICEAPPLICATIONSOLUTION_MAIN_FINANCIALSERVICEAPPLICATION_BIN_DEBUG_FINANCIALCONSULTANTDB_MDFConnectionString {
            get {
                return ((string)(this["_4619868F587328335CD4731366C17B86_SERVICEAPPLICATIONSOLUTION_MAIN_FINANCIALSERVIC" +
                    "EAPPLICATION_BIN_DEBUG_FINANCIALCONSULTANTDB_MDFConnectionString"]));
            }
        }
    }
}
